apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgresql.yaml
  - zookeeper.yaml
  - coordinator.yaml
  - broker.yaml
  - historical.yaml
  - middlemanager.yaml
  - router.yaml
